spring.application.name = USER-SERVICE

server.port=5054


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl.auto=update
spring.jpa.database=mysql

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization= true
